server:
  port: 8080
  servlet:
    context-path: /zyw
  tomcat:
    uri-encoding: utf-8



Spring:
  data:
    elasticsearch:
      cluster-ip: 127.0.0.1
      cluster-port: 9200
      scheme: https

person:
  name: 郑有为112233
  age: 24
  isBoss: true


